``numpy.distutils.compat`` has been removed
-------------------------------------------
This module contained only the function ``get_exception()``, which was used as::

    try:
        ...
    except Exception:
        e = get_exception()

Its purpose was to handle the change in syntax introduced in Python 2.6, from
``except Exception, e:`` to ``except Exception as e:``, meaning it was only
necessary for codebases supporting Python 2.5 and older.
